language: cpp
dist: trusty
compiler: g++
os: linux
sudo: required
addons: &gcc5
  apt:
    packages:
      - g++-5
      - gcc-5
      - libeigen3-dev 
      - libboost-all-dev
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - mkdir -p include
  - curl -o include/catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - sudo add-apt-repository ppa:kylelutz/compute -y
  - sudo apt-get update -q
  - sudo apt-get -y install boost-compute opencl-headers ocl-icd-opencl-dev
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
    fi;
  
script: SANITIZE_ADDRESS=NO make
